export const keyIsLoggedIn = "@isLoggedIn"
export const accessToken = "@accessToken"

export const keyIsBaseUrl = "@baseUrl"
export const keyIsPassword = "@password"
export const keyIsUserId = "@userId"
export const keyIsDeviceId = "@deviceId"
export const keyIsEmailId = "@emailId"
export const keyIsBranch = "@branch"
export const keyIsCmpCode = "@cmpCode"
export const keyIsOrgCode = "@orgCode"
export const keyIsName = "@name"
export const keyIsRoleCode = "@roleCode"
export const keyIsUserPrivileges = "@userPrivileges"
export const keyIsEmployeeCode = "@employeeCode"
export const keyIsTokenId = "@tokenId"
export const keyIsLicensePortalMap = "@licensePortalMap"
export const keyIsPasswordExpDate = "@passwordExpDate"